ignoreFiles = ["\\.qmd$", "\\.ipynb$", "\\.py$", "\\.Rmd$", "\\.r", "\\.R"]
baseURL = 'https://rorylawless.com/'
languageCode = 'en-gb'
title = 'Rory Lawless'
theme = 'paper'
[params]
favicon = 'favicon.svg'
appleTouchIcon = 'alien-touch-icon.png'
color = 'linen'
bluesky = 'rorylawless.com'
github = 'RoryLawless'
linkedin = 'rory-lawless'
rss = true
monoDarkIcon = true
[markup.goldmark.renderer]
unsafe = true
[markup]
[markup.highlight]
style = 'dracula'
