ignoreFiles = ["\\.qmd$", "\\.ipynb$", "\\.py$", "\\.Rmd$", "\\.r", "\\.R"]
baseURL = 'https://rorylawless.com/'
languageCode = 'en-gb'
title = 'Rory Lawless'
[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
[params]
favicon = 'favicon.svg'
appleTouchIcon = 'alien-touch-icon.png'
color = 'linen'
bluesky = 'rorylawless.com'
github = 'RoryLawless'
linkedin = 'rory-lawless'
rss = true
monoDarkIcon = true
[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'dracula'
[caches]
[caches.images]
dir = ':cacheDir/images'
[caches.modules]
dir = ':cacheDir/modules'
maxAge = -1
